### ISSUE TITLE
FAIL: SYCL with ComputeCpp: local_config_sycl has multiple matches

### ISSUE THREAD

**Issue by payload** [lukeiwanski/tensorflow#197]
https://github.com/lukeiwanski/tensorflow/blob/3a3671af98e32e0fe2eabb346288e62b9b7ffe12/third_party/sycl/sycl/BUILD.tpl#L24
This should be `true`.

Configuring for OpenCL SYCL with ComputeCpp is broken and not tested, right?
Error message on `bazel build -c opt --config=sycl //tensorflow/tools/pip_package:build_pip_package`
is ```
@local_config_sycl//sycl:using_sycl_ccpp
@local_config_sycl//sycl:using_sycl_trisycl
Multiple matches are not allowed unless one is unambiguously more specialized.
```

**Comment by lukeiwanski** [comment]
hi @payload 
I am assuming that you are on master branch.. which is mirror of the TF upstream.. 
can you give a try to the head of dev/amd_gpu ?

Luke

Note: yes you are right. That was a mix up when guys did merge in for triSYCL.

**Comment by payload** [comment]
Thank you for your short response :) dev/amd_gpu compiles fine. There was a linker issue. Bazel wanted to link libOpenCL.so but I had only libOpenCL.so.1 in my lib path. Quick fix with ln -s.

But now the real culprit is, that I am running the amdgpu-pro driver, which is obviously not supported by ComputeCpp and ends with an exception.

**Comment by lukeiwanski** [comment]
AMDGPU-Pro drivers _should_ work.. however it will depend on various factors like GPU and/or OS version.
I have access to FirePro W8100 and R9 Nano 
`$ wget --referer=http://support.amd.com https://www2.ati.com/drivers/linux/ubuntu/amdgpu-pro-17.30-465504.tar.xz`
above driver worked for them - see OpenCL & SYCL section on http://deep-beta.co.uk/tensorflow-1-3-on-ubuntu-16-04-lts/ for the instructions

**Comment by lukeiwanski** [comment]
@payload did it help?

**Comment by payload** [comment]
Can't test it anymore. Since the meltdown patches the amdgpu-pro driver doesn't work anymore on my machine.

**Comment by lukeiwanski** [comment]
I had the same thing. I had to revert kernel back 4.10 which is describe here: http://deep-beta.co.uk/tensorflow-1-x-on-ubuntu-16-04-lts/

I *do not* recommend doing that outside of a container eg. docker.

The alternative is to use AMDGPU-PRO 17.50.xxx drivers.. but they are exposing some odd behaviour - we are currently investigating

**Comment by lukeiwanski** [comment]
The patch for this problem is in the review now
