### ISSUE TITLE
Compile time is too long

### ISSUE THREAD

**Issue by subshall** [lukeiwanski/tensorflow#204]
system version ubuntu 14.4
bazel version 0.9.0
gcc version 4.8
computecpp version 0.5.1
GPU:r9 270x 4g
ComputeCpp Info (CE 0.5.1)

********************************************************************************

Toolchain information:

GLIBC version: 2.19
GLIBCXX: 20150426
This version of libstdc++ is supported.

********************************************************************************

Device Info:

Discovered 2 devices matching:
  platform    : <any>
  device type : <any>

--------------------------------------------------------------------------------
Device 0:

  Device is supported                     : UNTESTED - Device not tested on this OS
  CL_DEVICE_NAME                          : Pitcairn
  CL_DEVICE_VENDOR                        : Advanced Micro Devices, Inc.
  CL_DRIVER_VERSION                       : 1800.11 (VM)
  CL_DEVICE_TYPE                          : CL_DEVICE_TYPE_GPU 
--------------------------------------------------------------------------------
Device 1:

  Device is supported                     : UNTESTED - Vendor not tested on this OS
  CL_DEVICE_NAME                          : AMD FX(tm)-8300 Eight-Core Processor
  CL_DEVICE_VENDOR                        : AuthenticAMD
  CL_DRIVER_VERSION                       : 1800.11 (sse2,avx,fma4)
  CL_DEVICE_TYPE                          : CL_DEVICE_TYPE_CPU 

If you encounter problems when using any of these OpenCL devices, please consult
this website for known issues:
https://computecpp.codeplay.com/releases/v0.5.1/platform-support-notes

********************************************************************************

when i run sudo bazel build --local_resources 2048,.5,1.0 -c opt --config=sycl //tensorflow/tools/pip_package:build_pip_package
.............
WARNING: /home/zzt/.cache/bazel/_bazel_root/37963c447511203e3d4ee1aa24f9805c/external/grpc/WORKSPACE:1: Workspace name in /home/zzt/.cache/bazel/_bazel_root/37963c447511203e3d4ee1aa24f9805c/external/grpc/WORKSPACE (@com_github_grpc_grpc) does not match the name given in the repository's definition (@grpc); this will cause a build error in future versions
WARNING: /home/zzt/tensorflow-dev-amd_gpu/tensorflow/core/BUILD:1832:1: in includes attribute of cc_library rule //tensorflow/core:framework_headers_lib: '../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in /home/zzt/tensorflow-dev-amd_gpu/tensorflow/tensorflow.bzl:1150:30
WARNING: /home/zzt/tensorflow-dev-amd_gpu/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': No longer supported. Switch to SavedModel immediately.
WARNING: /home/zzt/tensorflow-dev-amd_gpu/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': No longer supported. Switch to SavedModel immediately.
INFO: Analysed target //tensorflow/tools/pip_package:build_pip_package (257 packages loaded).
INFO: Found 1 target...
INFO: From Compiling tensorflow/core/framework/op_gen_lib.cc [for host]:
tensorflow/core/framework/op_gen_lib.cc:269:13: warning: unused function 'RenameInDocs' [-Wunused-function]
static void RenameInDocs(const string& from, const string& to, OpDef* op_def) {
            ^
1 warning generated.
In file included from <built-in>:1:
./tensorflow/core/framework/op_gen_lib.cc:269:13: warning: unused function 'RenameInDocs' [-Wunused-function]
static void RenameInDocs(const string& from, const string& to, OpDef* op_def) {
            ^
1 warning generated.
INFO: From Compiling tensorflow/core/common_runtime/gpu/process_state.cc [for host]:
tensorflow/core/common_runtime/gpu/process_state.cc:54:6: warning: unused function 'useCudaMallocAllocator' [-Wunused-function]
bool useCudaMallocAllocator() {
     ^
tensorflow/core/common_runtime/gpu/process_state.cc:60:6: warning: unused function 'useCudaMemoryGuardAllocator' [-Wunused-function]
bool useCudaMemoryGuardAllocator() {
     ^
2 warnings generated.
In file included from <built-in>:1:
./tensorflow/core/common_runtime/gpu/process_state.cc:54:6: warning: unused function 'useCudaMallocAllocator' [-Wunused-function]
bool useCudaMallocAllocator() {
     ^
./tensorflow/core/common_runtime/gpu/process_state.cc:60:6: warning: unused function 'useCudaMemoryGuardAllocator' [-Wunused-function]
bool useCudaMemoryGuardAllocator() {
     ^
2 warnings generated.
INFO: From Compiling tensorflow/stream_executor/stream.cc [for host]:
tensorflow/stream_executor/stream.cc: In function 'std::string perftools::gputools::{anonymous}::ToVlogString(perftools::gputools::dnn::DataType)':
tensorflow/stream_executor/stream.cc:184:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
INFO: From Compiling tensorflow/core/framework/op_kernel.cc [for host]:
tensorflow/core/framework/op_kernel.cc:962:8: warning: unused function 'FindKernelRegistration' [-Wunused-function]
Status FindKernelRegistration(const DeviceType& device_type, const Node& node,
       ^
1 warning generated.
In file included from <built-in>:1:
./tensorflow/core/framework/op_kernel.cc:962:8: warning: unused function 'FindKernelRegistration' [-Wunused-function]
Status FindKernelRegistration(const DeviceType& device_type, const Node& node,
       ^
1 warning generated.
INFO: From Compiling external/snappy/snappy-sinksource.cc [for host]:
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: unrecognized command line option "-Wno-shift-negative-value" [enabled by default]
INFO: From Compiling external/snappy/snappy-stubs-internal.cc [for host]:
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: unrecognized command line option "-Wno-shift-negative-value" [enabled by default]
INFO: From Compiling external/snappy/snappy.cc [for host]:
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++ [enabled by default]
external/snappy/snappy.cc: In member function 'void snappy::SnappySinkAllocator::Flush(size_t)':
external/snappy/snappy.cc:1403:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < blocks_.size(); ++i) {
                                      ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-shift-negative-value" [enabled by default]
INFO: From Compiling external/snappy/snappy-c.cc [for host]:
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: unrecognized command line option "-Wno-shift-negative-value" [enabled by default]
INFO: From ProtoCompile tensorflow/contrib/lite/toco/toco_flags.pb.cc:
bazel-out/k8-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
bazel-out/k8-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
INFO: From Compiling tensorflow/contrib/fused_conv/ops/fused_conv2d_bias_activation_op.cc [for host]:
tensorflow/contrib/fused_conv/ops/fused_conv2d_bias_activation_op.cc:31:8: warning: unused function 'GetAllActivationModeAttrString' [-Wunused-function]
string GetAllActivationModeAttrString() { return "activation_mode: {'Relu'}"; }
       ^
1 warning generated.
In file included from <built-in>:1:
./tensorflow/contrib/fused_conv/ops/fused_conv2d_bias_activation_op.cc:31:8: warning: unused function 'GetAllActivationModeAttrString' [-Wunused-function]
string GetAllActivationModeAttrString() { return "activation_mode: {'Relu'}"; }
       ^
1 warning generated.
[1,238 / 1,429] 8 actions, 1 running
    Executing genrule //tensorflow/python:bitwise_ops_pygenrule; 31425s local
    [Sched] .../contrib/input_pipeline:input_pipeline_ops_pygenrule; 31433s
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: build interrupted

  there is a lot of warning and compile time is very long .stuck in one action for 9 hours.i tried gcc4.9/5.4.but it doesn't work .and i change bazel option opt to fastbuild.also doesn't work.so i need some help .

**Comment by lukeiwanski** [comment]
Hi @subshall 
Thanks for the report. Ubuntu 14.04 is approaching EOL ( 2019 ) and I would recommend considering a move to Ubuntu 16.04.
As of this issue we did encounter a deadlock when combining dlopen and AMD's fglrx drivers
It seems like mutext gets corrupted at some point and stuck in dead lock. For us a work around was to add `LD_PRELOAD={path to libOpenCL.so}` to `--action_env`
Could you try this command:
```bazel build --action_env=LD_PRELOAD={path/to/libOpenCL.so} --local_resources 2048,.5,1.0 -c opt --config=sycl``` 
note: I would not recommend compiling TF as a sudo

**Comment by subshall** [comment]
hello lukeiwanski,i try to build use this
bazel build --action_env=LD_PRELOAD={path/to/libOpenCL.so} --local_resources 2048,.5,1.0 -c opt --config=sycl .
 it works,but when i import tensorflow.the output is 
zzt@zzt-To-be-filled-by-O-E-M:~/tensorflow-dev-amd_gpu/_python_build$ python
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
2018-01-27 14:07:59.578928: I ./tensorflow/core/platform/s3/aws_logging.cc:53] Initializing Curl library
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "tensorflow/python/framework/framework_lib.py", line 76, in <module>
    from tensorflow.python.framework.ops import Graph
  File "tensorflow/python/framework/ops.py", line 54, in <module>
    from tensorflow.python.platform import app
  File "tensorflow/python/platform/app.py", line 24, in <module>
    from tensorflow.python.platform import flags
  File "tensorflow/python/platform/flags.py", line 25, in <module>
    from absl.flags import *  # pylint: disable=wildcard-import
ImportError: No module named absl.flags
import again
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name pywrap_tensorflow

**Comment by lukeiwanski** [comment]
run: `pip install absl-py`

Someone had the same issue: https://stackoverflow.com/questions/48490260/no-module-named-absl-error-when-i-import-tensorflow

**Comment by mirh** [comment]
I just successfully compiled the thing, on fglrx 1800.11. No problems to report. 

Yes, it took 20 hours...  On a cpu with the power of a toaster. Almost [10 times](https://www.anandtech.com/bench/CPU/55) less than yours. 

Only remotely sensible reason I can think, is your ancient OS.

**Comment by lukeiwanski** [comment]
Once this https://github.com/lukeiwanski/tensorflow/pull/214 gets in, the compilation time should be reduced ( as we finally remove calls to python )

Please re-open if it's still a problem
