### ISSUE TITLE
InvalidArgumentError: activation input is not finite. : Tensor had NaN values

### ISSUE THREAD

**Issue by mirh** [lukeiwanski/tensorflow#246]
So.. After forward porting 1e0dd427cb6ae0a295e7a2782746513f3646aba2 to 1.8 branch
After compiling with `--cxxopt="-sycl-compress-name"`
After waiting a godawful amount of time (it seems, compared to 1.6, compilation takes at least 50% more)

I'm getting this:
```
[@ tensorflow-integration-1.8]$ python ../models/tutorials/image/imagenet/classify_image.py
/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-06-16 00:38:34.304999: W ./tensorflow/core/framework/op_def_util.cc:346] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
2018-06-16 00:38:36.568416: I ./tensorflow/core/common_runtime/sycl/sycl_device.h:70] Found following OpenCL devices:
2018-06-16 00:38:36.568566: I ./tensorflow/core/common_runtime/sycl/sycl_device.h:72] id: 0, type: GPU, name: Loveland, vendor: Advanced Micro Devices, Inc., profile: FULL_PROFILE
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: activation input is not finite. : Tensor had NaN values
	 [[Node: mixed_1/tower_1/conv/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="activation input is not finite.", _device="/job:localhost/replica:0/task:0/device:CPU:0"](mixed_1/tower_1/conv/batchnorm/_109)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../models/tutorials/image/imagenet/classify_image.py", line 227, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "../models/tutorials/image/imagenet/classify_image.py", line 193, in main
    run_inference_on_image(image)
  File "../models/tutorials/image/imagenet/classify_image.py", line 157, in run_inference_on_image
    {'DecodeJpeg/contents:0': image_data})
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: activation input is not finite. : Tensor had NaN values
	 [[Node: mixed_1/tower_1/conv/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="activation input is not finite.", _device="/job:localhost/replica:0/task:0/device:CPU:0"](mixed_1/tower_1/conv/batchnorm/_109)]]

Caused by op 'mixed_1/tower_1/conv/CheckNumerics', defined at:
  File "../models/tutorials/image/imagenet/classify_image.py", line 227, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "../models/tutorials/image/imagenet/classify_image.py", line 193, in main
    run_inference_on_image(image)
  File "../models/tutorials/image/imagenet/classify_image.py", line 144, in run_inference_on_image
    create_graph()
  File "../models/tutorials/image/imagenet/classify_image.py", line 127, in create_graph
    _ = tf.import_graph_def(graph_def, name='')
  File "/usr/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 513, in import_graph_def
    _ProcessNewOps(graph)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 303, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3558, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3558, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3446, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1736, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): activation input is not finite. : Tensor had NaN values
	 [[Node: mixed_1/tower_1/conv/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="activation input is not finite.", _device="/job:localhost/replica:0/task:0/device:CPU:0"](mixed_1/tower_1/conv/batchnorm/_109)]]
```
It also takes like ten minutes (vs 30 seconds of the cpu version that successfully terminate) to get here.. But probably it's still due to the same problem

**Comment by Rbiessy** [comment]
It is often slower with SYCL because the runtime compiles all the OpenCL kernels in TF so that takes some time.
And yes unfortunately we still have nans in some operations. It is not easy to figure out exactly which operation caused it in full fledged examples. I know sometimes we have some precision issue where very small number are used and the result is finite on CPU but not in OpenCL.
On a side note this example works with TF 1.6 but I know you need 1.8.

**Comment by mirh** [comment]
1.6 produces the same result. 
I just "strove" to try 1.8 because I thought that was the working branch for you. 

EDIT: oh, and kernels having to builds certainly explain the low performance on my teapot system

**Comment by Rbiessy** [comment]
I tried with my dev branch based on TF 1.6 which is pretty close to Luke's dev/amd_gpu and with TF 1.8 with an Eigen bump, they both worked for me.
I compiled the whl with
`bazel build --verbose_failures -c opt --config=sycl --cxxopt=-no-serial-memop //tensorflow/tools/pip_package:build_pip_package`
My output with the latest models repository is:
`2018-06-19 13:46:24.655095: W ./tensorflow/core/framework/op_def_util.cc:346] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
2018-06-19 13:46:24.736635: I ./tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-06-19 13:46:24.811319: I ./tensorflow/core/common_runtime/sycl/sycl_device.h:70] Found following OpenCL devices:
2018-06-19 13:46:24.811356: I ./tensorflow/core/common_runtime/sycl/sycl_device.h:72] id: 0, type: GPU, name: Fiji, vendor: Advanced Micro Devices, Inc., profile: FULL_PROFILE
giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca (score = 0.89107)
indri, indris, Indri indri, Indri brevicaudatus (score = 0.00779)
lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens (score = 0.00296)
custard apple (score = 0.00147)
earthstar (score = 0.00117)`

I'm not sure what could go wrong for you. It seems to me that some OpenCL drivers have a bad floating precision.

**Comment by mirh** [comment]
Well, they are [old¿] amd drivers after all /s
Which indeed, even with your last instructions result in the same unfortunately.

**Comment by Rbiessy** [comment]
That's unfortunate, I don't think this is something we can fix in the backend.
To me the only real solution is to write the network differently to better account for rounding errors.

**Comment by mirh** [comment]
Oh, by the way.. Could my disabling of half and doubles have anything to do with this?
Or the fact that "single precision floating point capabilities" of GPU/CPU are different (namely, the former lacks *Denorms* of the 6 entries)?

EDIT: CL_FP_CORRECTLY_ROUNDED_DIVIDE_SQRT capability is not reported at all anywhere though

**Comment by Rbiessy** [comment]
Hum so disabling half and double should be fine. Most, if not all, the samples are using float anyway. If you were to try and use an operation on SYCL that is not registered for a type, the operation would either be placed on the CPU or would throw an exception if the GPU placement was forced.

Your comment about `CL_FP_CORRECTLY_ROUNDED_DIVIDE_SQRT` is interesting. I do have it on for floats with my setup. It reminds me that we always compile with `-Xclang -cl-fp32-correctly-rounded-divide-sqrt` which will enable the flag when building the kernels (in `third_party/sycl/crosstool/CROSSTOOL.tpl`). I'll try to give it a spin without this flag when I have time.

**Comment by mirh** [comment]
Well, there's something very fishy going on. 
`-cl-denorms-are-zero` is supposed to be ignored at runtime (afaiu) on my hardware that has CL_FP_DENORM=0. And that's all good and well. 

But I just tried [this more comprehensive clinfo](https://github.com/Oblomov/clinfo), and I can attest I'm indeed not supporting correctly rounded stuff. 
And [I should get](https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/clBuildProgram.html#id-1.6.10) to the very least an error for it??

**Comment by Rbiessy** [comment]
I noticed the spec says that enabling `-cl-fp32-correctly-rounded-divide-sqrt` will cause an error if not supported but I wouldn't be surprised if most driver just ignore it instead.
However after I compiled without the flag and ran the model again, I still have the same result. So I'm not sure what is happening but your issue may still be related to that. I can very easily imagine the model dividing by a number close to 0 which will produce unexpected inf.

**Comment by mirh** [comment]
So.. I tried to do the same.. But compilation for some reason was quite.. crashy. 
After restarting it a couple of times, it's almost finished, but I'm getting this eventually: 
```
[@ tensorflow-dev-amd_gpu]$ bazel build --verbose_failures -c opt --config=sycl --cxxopt="-sycl-compress-name" --cxxopt=-no-serial-memop //tensorflow/tools/pip_package:build_pip_package
WARNING: /tensorflow-dev-amd_gpu/tensorflow/core/BUILD:1896:1: in includes attribute of cc_library rule //tensorflow/core:framework_headers_lib: '../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in /tensorflow-dev-amd_gpu/tensorflow/tensorflow.bzl:1185:30
WARNING: /tensorflow-dev-amd_gpu/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': No longer supported. Switch to SavedModel immediately.
WARNING: /tensorflow-dev-amd_gpu/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': No longer supported. Switch to SavedModel immediately.
INFO: Analysed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded).
INFO: Found 1 target...
ERROR: /tensorflow-dev-amd_gpu/tensorflow/python/BUILD:3170:1: Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed (Exit 1): compute failed: error executing command 
  (cd /home/~/.cache/bazel/_bazel/bfa925de178436ba85f27964c552631c/execroot/org_tensorflow && \
  exec env - \
    COMPUTECPP_TOOLKIT_PATH=/opt/ComputeCpp-CE-0.8.0-Ubuntu-16.04-x86_64 \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/lib/python3.6/site-packages \
    TF_NEED_COMPUTECPP=1 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=1 \
    TF_SYCL_BITCODE_TARGET=spir64 \
  /opt/ComputeCpp-CE-0.8.0-Ubuntu-16.04-x86_64/bin/compute -shared -o bazel-out/k8-py3-opt/bin/tensorflow/python/_pywrap_tensorflow_internal.so '-Wl,-rpath,$ORIGIN/../../_solib_local/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow' '-Wl,-rpath,$ORIGIN/../../_solib_local/_U@local_Uconfig_Usycl_S_Ssycl_Csyclrt___Uexternal_Slocal_Uconfig_Usycl_Ssycl_Slib' -Lbazel-out/k8-py3-opt/bin/_solib_local/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow -Lbazel-out/k8-py3-opt/bin/_solib_local/_U@local_Uconfig_Usycl_S_Ssycl_Csyclrt___Uexternal_Slocal_Uconfig_Usycl_Ssycl_Slib -Wl,--version-script bazel-out/k8-py3-opt/bin/tensorflow/python/pywrap_tensorflow_internal_versionscript.lds '-Wl,-rpath,$ORIGIN/,-rpath,$ORIGIN/..' -Wl,-soname,_pywrap_tensorflow_internal.so -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -B/usr/bin/ -no-canonical-prefixes -Wl,-no-as-needed -Wl,-z,relro,-z,now '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,--allow-shlib-undefined -Wl,--gc-sections -Wl,@bazel-out/k8-py3-opt/bin/tensorflow/python/_pywrap_tensorflow_internal.so-2.params)
/usr/bin/ld: bazel-out/k8-py3-opt/bin/tensorflow/core/kernels/libreduction_ops.pic.lo(reduction_ops_min.pic.o)(.text._ZN2cl4sycl7program25create_program_for_kernelIN5Eigen10TensorSycl8internal16ReductionFunctorIKNS3_9TensorMapINS3_6TensorIKfLi2ELi1ElEELi16ENS3_11MakePointerEEEN7utility5tuple5TupleIJNS3_6DSizesIlLi2EEEEEENSG_IJNS3_5arrayIbLm2EEENSH_IlLi1EEENSK_IlLm1EEESN_SN_SN_EEENSG_IJNS3_11RangeAccessILNS0_6access4modeE0EEEEEEKNS3_9IndexListINS3_10type2indexILl0EEEJEEENS3_8internal10MinReducerIfEElEEEES1_NS0_7contextE[_ZN2cl4sycl7program25create_program_for_kernelIN5Eigen10TensorSycl8internal16ReductionFunctorIKNS3_9TensorMapINS3_6TensorIKfLi2ELi1ElEELi16ENS3_11MakePointerEEEN7utility5tuple5TupleIJNS3_6DSizesIlLi2EEEEEENSG_IJNS3_5arrayIbLm2EEENSH_IlLi1EEENSK_IlLm1EEESN_SN_SN_EEENSG_IJNS3_11RangeAccessILNS0_6access4modeE0EEEEEEKNS3_9IndexListINS3_10type2indexILl0EEEJEEENS3_8internal10MinReducerIfEElEEEES1_NS0_7contextE]+0x40152): reloc against `strlen@@GLIBC_2.2.5': error 4
/usr/bin/ld: final link failed: Nonrepresentable section on output
compute: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Rbiessy** [comment]
Hum ok I've never seen that... We compile with `-fPIE` but maybe we should compile with `-fPIC` instead. It may solve your issue?

**Comment by mirh** [comment]
Yes, it did. 
But I'm still back to square one again now >.<

**Comment by mirh** [comment]
I'm still getting this error on imagenet, but mnist NaN losses (for as much I wouldn't really be able to rate its *performance*) actually got fixed with computecpp 0.9.0

EDIT: ok nvm, after a third long run, they are back.

**Comment by Rbiessy** [comment]
I'm sorry there isn't much we can do about that since it comes down to the precision of your driver in the end.

**Comment by mirh** [comment]
I just got a new line, just for the records (during those odd runs where it fails)
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: MaxPool input is not finite. : Tensor had Nan values
  [[Node: mixed_3/pool/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="MaxPool input is not finite.", _device="/job:localhost/replica:0/task:0/device:SYCL:0"](mixed_2/join)]]
  [[Node: softmax/_7 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:SYCL:0", send_device_incarnation=1, tensor_name="edge_1630_softmax", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by Rbiessy** [comment]
Well this only confirms that some operations before MaxPool is producing NaNs. This is most likely due to a division or a sqrt but I still don't see how we could solve that in TF.

**Comment by mirh** [comment]
http://developer.amd.com/wordpress/media/2012/10/AMD_Evergreen-Family_Instruction_Set_Architecture.pdf#page=83
Could the instruction set not having FP operations names actually correspond IEEE behavior by default be related to this?

**Comment by Rbiessy** [comment]
It could be but from what I can see the differences between non-IEEE and IEEE operations are only in edge cases. I think if a model is using only real floating values it will not make a difference to use the IEEE equivalent.
