### ISSUE TITLE
Cannot compile, Illegal ambiguous match on configurable attribute "deps" in @jpeg//:jpeg:

### ISSUE THREAD

**Issue by metal3d** [lukeiwanski/tensorflow#247]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu:latest (Docker)
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
1.6.0
- **Python version**: 
Python 3.6.5
- **Bazel version (if compiling from source)**:
 bazel version
Build label: 0.14.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 8 12:17:35 2018 (1528460255)
Build timestamp: 1528460255
Build timestamp as int: 1528460255

- **GCC/Compiler version (if compiling from source)**:

### Describe the problem
I'm trying to build 1.6.0 release from this repository, inside a ubuntu docker container (fedora doesn't provides gcc 6 and g++ 6)

After having use ./configure given /usr/bin/python3 as python binary, see the following log.

Note that I followed https://github.com/tensorflow/tensorflow/issues/18450 report that says to downgrade bazel and use GCC-6 and G++-6

### Source code / logs
```
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
...........
ERROR: /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/jpeg/BUILD:126:12: Illegal ambiguous match on configurable attribute "deps" in @jpeg//:jpeg:
@jpeg//:k8
@jpeg//:armeabi-v7a
Multiple matches are not allowed unless one is unambiguously more specialized.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: 

/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/jpeg/BUILD:126:12: Illegal ambiguous match on configurable attribute "deps" in @jpeg//:jpeg:
@jpeg//:k8
@jpeg//:armeabi-v7a
Multiple matches are not allowed unless one is unambiguously more specialized.
INFO: Elapsed time: 11.715s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (127 packages loaded)
    currently loading: tensorflow/core/kernels

```

build config
```
cat ../.tf_configure.bazelrc 
build --action_env PYTHON_BIN_PATH="/usr/bin/python3"
build --action_env PYTHON_LIB_PATH="/usr/lib/python3/dist-packages"
build --force_python=py3
build --host_force_python=py3
build --python_path="/usr/bin/python3"
build --define with_jemalloc=true
build:gcp --define with_gcp_support=true
build:hdfs --define with_hdfs_support=true
build:s3 --define with_s3_support=true
build:kafka --define with_kafka_support=true
build:xla --define with_xla_support=true
build:gdr --define with_gdr_support=true
build:verbs --define with_verbs_support=true
build --action_env TF_NEED_OPENCL_SYCL="1"
build --action_env HOST_CXX_COMPILER="/usr/bin/g++-6"
build --action_env HOST_C_COMPILER="/usr/bin/gcc-6"
build --action_env TF_NEED_COMPUTECPP="0"
build --action_env TRISYCL_INCLUDE_DIR="/usr/local/triSYCL/include"
build --action_env TF_USE_DOUBLE_SYCL="1"
build --action_env TF_USE_HALF_SYCL="0"
build --action_env TF_NEED_CUDA="0"
build --define grpc_no_ares=true
build:opt --copt=-march=native
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build --copt=-DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK
build --host_copt=-DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK

```

**Comment by metal3d** [comment]
Ok, the release is not ok but it seems that the master branch can compile. Several hours it compiles, so I can close this issue.

**Comment by Rbiessy** [comment]
Hello, careful as the master branch has very little SYCL support.
It would be best to use the eigen_sycl branch of the Codeplay repository here: https://github.com/codeplaysoftware/tensorflow
You will see the same issue that you described here. This comes from bazel; you have to use bazel 0.11.1 to fix it. We will be able to use the latest bazel version again once we merge TF 1.8.

Also make sure to build with the sycl configuration. A typical command to build the pip package with sycl support is:
`bazel build --verbose_failures -c opt --config=sycl //tensorflow/tools/pip_package:build_pip_package`

**Comment by metal3d** [comment]
I'll take a look later, thanks for information.
Unfortunately I need time to make tests, and I've got so many work in parallel...

**Comment by Rbiessy** [comment]
That's alright, by the way the instructions on our website have been updated now so you should have a look at that if you have time https://developer.codeplay.com/computecppce/latest/getting-started-with-tensorflow
