### ISSUE TITLE
Error when building tensorflow-sycl with triSYCL

### ISSUE THREAD

**Issue by dmidge8** [lukeiwanski/tensorflow#255]
Hi,

### The compilation problem

Whenever I try to compile this version of tensorflow with triSYCL, I get the following error.

```
ERROR: no such package '@local_config_sycl//crosstool': Traceback (most recent call last):
        File "/home/me/Workspace/tensorflow-triSYCL-git/src/tensorflow/third_party/sycl/sycl_configure.bzl", line 231
                _tpl(repository_ctx, "crosstool:trisycl..., ...})
        File "/home/me/Workspace/tensorflow-triSYCL-git/src/tensorflow/third_party/sycl/sycl_configure.bzl", line 129, in _tpl
                repository_ctx.template(out, Label(("//third_party/sycl/%s...)), ...)
com.google.devtools.build.lib.bazel.repository.skylark.SkylarkPath cannot be cast to java.lang.String
```

### The compilation configuration

To compile, I use the following commands:
```
  export PYTHON_BIN_PATH=/usr/bin/python
  export USE_DEFAULT_PYTHON_LIB_PATH=1
  export CC_OPT_FLAGS="-march=native -mfpmath=sse -O2 -pipe"
  export TF_DOWNLOAD_CLANG=0
  export TF_CUDA_CLANG=0
  export TF_NEED_CUDA=0
  export TF_NEED_JEMALLOC=0
  export TF_NEED_GCP=0
  export TF_NEED_HDFS=0
  export TF_ENABLE_XLA=0
  export TF_NEED_GDR=0
  export TF_NEED_VERBS=0
  export TF_NEED_MPI=0
  export TF_NEED_S3=0
  export TF_NEED_KAFKA=0
  export TF_NEED_TENSORRT=0
  export TF_SET_ANDROID_WORKSPACE=0
  export TF_NEED_OPENCL=1
  export TF_NEED_OPENCL_SYCL=1
  export TF_NEED_COMPUTECPP=0
  export TF_SYCL_BITCODE_TARGET=spir64
  export TRISYCL_INCLUDE_DIR="/usr/include/CL/sycl"
  export COMPUTE=:0

  ./configure
  bazel build --config=opt --config=sycl //tensorflow:libtensorflow.so //tensorflow/tools/pip_package:build_pip_package
  
```

Please note that I am not using ComputeCpp. If I am not wrong, it should only use triSYCL. But it doesn't compile.
What am I doing wrong? It is looking like there is a missing dependency...

------------------------

### System information
- **OS Platform and Distribution**: Archlinux 64 bit
- **TensorFlow installed from source**
- **TensorFlow version**: 1.8
- **Python version**: 3.7
- **Bazel version**: 0.16
- **GCC/Compiler version **: 8.2

Thanks!

**Comment by keryell** [comment]
You should use ComputeCpp 1.0+ since it is the only conforming implementation for now.
triSYCL is still far from being conforming...

**Comment by Rbiessy** [comment]
I'm afraid triSYCL support broke sometime ago because of changes from upstream in the build system. We haven't tried to fix them for triSYCL.

**Comment by keryell** [comment]
You should try to fix it... :-)

**Comment by Rbiessy** [comment]
Yes I will try one day!

**Comment by dmidge8** [comment]
I concur what keryell says. Because this package is basically the only implementation that is working on AMD GPUs. And it is not fully open source.
If it was working with triSYCL, if I am correct, it would be. Which would be great! :o)

Should this issue really be closed? I guess it is more a postponed (to a time to be determined) feature request then, isn't it?

**Comment by Rbiessy** [comment]
Yes I consider it like a postponed feature request too.
