### ISSUE TITLE
Compilation Error with ComputeCPP

### ISSUE THREAD

**Issue by RainbowZephyr** [lukeiwanski/tensorflow#256]
## System information

1. OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
2. TensorFlow installed from (source or binary): master branch
3. Python version: 3.7
4. Bazel version (if compiling from source): 0.16.1
5. GCC/Compiler version (if compiling from source): 8.2.1
6. GPU model and memory: intel HD 4000
7. ComputeCPP version: 0.10
8. Exact command to reproduce:

> bazel build -c opt --config=sycl //tensorflow:libtensorflow.so //tensorflow/tools/pip_package:build_pip_package

Exact error:

```sh
./tensorflow-opencl/tensorflow/core/BUILD:309:1: C++ compilation of rule '//tensorflow/core:platform_base' failed (Exit 1): computecpp failed: error executing command 
  (cd /home/user/.cache/bazel/_bazel_user/f05292afceb05a4328135c7cfb85dd8e/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/opt/cuda/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl \
    PWD=/proc/self/cwd \
  external/local_config_sycl/crosstool/computecpp -fPIE -fno-omit-frame-pointer -Wall -msse3 -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -MD -MF bazel-out/host/bin/tensorflow/core/_objs/platform_base/1/env_time.d '-frandom-seed=bazel-out/host/bin/tensorflow/core/_objs/platform_base/1/env_time.o' -iquote . -iquote bazel-out/host/genfiles -iquote bazel-out/host/bin -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote bazel-out/host/bin/external/bazel_tools -g0 -g0 -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare -fno-exceptions '-ftemplate-depth=900' -msse3 -pthread -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c tensorflow/core/platform/env_time.cc -o bazel-out/host/bin/tensorflow/core/_objs/platform_base/1/env_time.o)
Traceback (most recent call last):
  File "external/local_config_sycl/crosstool/computecpp", line 94, in <module>
    sys.exit(main())
  File "external/local_config_sycl/crosstool/computecpp", line 63, in main
    if not '.parallel_for' in preprocessed_file_str:
TypeError: a bytes-like object is required, not 'str'
```

**Comment by Rbiessy** [comment]
Hello,
If you want to use TensorFlow with ComputeCpp now you should use the eigen_sycl branch of the [Codeplay repository](https://github.com/codeplaysoftware/tensorflow/tree/eigen_sycl).
For now TensorFlow 1.6 is supported with Bazel 0.11.1 and ComputeCpp CE 1.0.0. We are working on supporting a more recent version of TensorFlow.

**Comment by RainbowZephyr** [comment]
Hello, 
I thought this repo was for using tensorflow with computecpp. What is supported in this repo then?

Thanks

**Comment by mirh** [comment]
I thought yours was the latest legit branch?
https://github.com/Rbiessy/tensorflow/tree/dev/amd_gpu

**Comment by Rbiessy** [comment]
Hello,
@RainbowZephyr sorry for the late reply. This repository won't be updated anymore so we try to redirect the attention to the official company's repository instead.
@mirh mine is for development only. So it is indeed the latest but use it at your own risk!
