### ISSUE TITLE
TensorFlow Distributed API is not working due to this minor issue

### ISSUE THREAD

**Issue by lu4** [lukeiwanski/tensorflow#257]
Hi, you have bug here:
https://github.com/lukeiwanski/tensorflow/blob/master/tensorflow/core/util/device_name_utils.cc#L169

due to `ParseFullName` and maybe other related methods can not parse Device names such as `SYCL`, only CPU/cpu and GPU/gpu

The problem appears as a result of a usage of distributed tensorflow api. The following code is based on examples described here http://amid.fish/assets/Distributed%20TensorFlow%20-%20A%20Gentle%20Introduction.html

**Here's server code (in your case IPs will most probably be different):**
```
import tensorflow as tf

with tf.device("/job:ps/task:0"):
    var = tf.Variable(0.0, name='var')

ps_addresses = ["192.168.1.6:50000"]
worker_addresses = ["192.168.1.4:60000"]

cluster = tf.train.ClusterSpec({"ps": ps_addresses, "worker": worker_addresses})
server = tf.train.Server(cluster, job_name="ps", task_index=0)
sess = tf.Session(target=server.target)

print("Parameter server: waiting for cluster connection...")
sess.run(tf.report_uninitialized_variables())
print("Parameter server: cluster ready!")    
    
print("Parameter server: initializing variables...")
sess.run(tf.global_variables_initializer())
print("Parameter server: variables initialized")
```

**Here's client code:**
```
import tensorflow as tf

from netifaces import interfaces, ifaddresses, AF_INET

with tf.device("/job:ps/task:0"):
    var = tf.Variable(0.0, name='var')

ps_addresses = ["192.168.1.6:50000"]
worker_addresses = ["192.168.1.4:60000"] #, "192.168.1.42:60000", "192.168.1.43:60000", "192.168.1.44:60000", "192.168.1.46:60000", "192.168.1.23:60000"]
    
def get_address(address, worker_addresses):
    for worker_address in worker_addresses:
        if worker_address.startswith(address):
            return worker_address
    return None
    
def worker_address(worker_addresses):
    for name in interfaces():
        for record in ifaddresses(name).setdefault(AF_INET, [{'addr':'No IP addr'}]):
            address = get_address(record['addr'], worker_addresses)
            
            if address is not None:
                return address
    return None
    
my_address = worker_address(worker_addresses)
my_address_index = worker_addresses.index(my_address)

print(my_address)

cluster = tf.train.ClusterSpec({"ps": ps_addresses, "worker": worker_addresses})
server = tf.train.Server(cluster, job_name="worker", task_index=my_address_index)
sess = tf.Session(config=tf.ConfigProto(device_count={'SYCL': 8}), target=server.target)

print("Worker %d: waiting for cluster connection..." % my_address_index)
sess.run(tf.report_uninitialized_variables())
print("Worker %d: cluster ready!" % my_address_index)

while sess.run(tf.report_uninitialized_variables()):
    print("Worker %d: waiting for variable initialization..." % my_address_index)
    sleep(1.0)

print("Worker %d: variables initialized" % my_address_index)
```

**Comment by Rbiessy** [comment]
Hi, thanks for the report.

This is indeed an issue unfortunately we don't support distributed runtime. I'm afraid there would be more changes than just this but it would be interesting to see if this lets you go further. Would you be able to test the change you suggest by any chance?

Also I should mention we have a more recent version of TF using SYCL [here](https://github.com/codeplaysoftware/tensorflow/tree/eigen_sycl) with updated instructions on our [website](https://developer.codeplay.com/computecppce/latest/getting-started-with-tensorflow). Note that you can always use the latest version of the eigen_sycl branch if you have the latest version of ComputeCpp. Please use this other repository for future tickets.

**Comment by lu4** [comment]
I will try to build a new version from your link and check, but do you have it fixed there?

**Comment by Rbiessy** [comment]
No, we haven't touched anything related to distributed runtime. But it is using TF 1.9 instead of 1.6 here. Also it would be easier for us to patch the latest version if needed.
