### ISSUE TITLE
Consider to Change repository name

### ISSUE THREAD

**Issue by talregev** [lukeiwanski/tensorflow#258]
When I looking for tensor opencl I look in the name of the repository first.
So I skip this repository many times (even if in the resolt it shown) just because the name.
tensorflow opencl or tensorflow cl it will be nice.

Thanks again for your time!

**Comment by rodburns** [comment]
This branch is out of date. For the latest OpenCL and SYCL branch see https://github.com/codeplaysoftware/tensorflow

**Comment by talregev** [comment]
thank you.

**Comment by talregev** [comment]
Why this repository is out of date?
last commit here from Jun 24, 2018.
The codeplaysoftware repository last commit from Oct 25, 2017

**Comment by Rbiessy** [comment]
You have to use the eigen_sycl branch which last commit was from Nov 05, 2018.
You will also need to follow the instructions here: https://developer.codeplay.com/computecppce/latest/getting-started-with-tensorflow. Note that if you want to use our latest version of TF you have to get the latest version of ComputeCpp as well.

**Comment by talregev** [comment]
Thank you.
